export const tempMovieDetail = {
  adult: false,
  backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
  belongs_to_collection: {
    id: 544669,
    name: "Minions Collection",
    poster_path: "/yG4ZgrIinuQJGuFQfXZc1fB2UHN.jpg",
    backdrop_path: "/62Qe28oi9PaK3P2ljDYUDTGAyST.jpg",
  },
  budget: 85000000,
  genres: [
    { id: 16, name: "Animation" },
    { id: 12, name: "Adventure" },
    { id: 35, name: "Comedy" },
    { id: 14, name: "Fantasy" },
  ],
  homepage: "https://www.minionsmovie.com/",
  id: 438148,
  imdb_id: "tt5113044",
  original_language: "en",
  original_title: "Minions: The Rise of Grasda;ksasdsadas asdasdaasdas djljd;lkjalksjdal;kju",
  overview:
    "A fanboy of a supervillain supergroup kalksjdhaslkjdfhaslkdjhaslkdjhas kjdahsd jasdkjahs lkasjdh laskjh asjdhaj hh jhasdha sldjhasl djhaskdj halkaskjdh askjdha kdhak haslkjdhaskjhd aksljhdla ksjhdaks jhakjdh alkjdh laksjhdalksjhdalk jhdalkj dhaslkj dhlkjh kljdahsldk jhasdj haskdja kjdhaslk jdhaslkdj halskjdh laskjdasl ikdhalk sjhdlaksj dhaslkjdh aslkjdh aksljhdlkajshd kajshdlk jhsdk j kjdlkajs dlkaj slkdklnown as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
  popularity: 2866.79,
  poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
  production_companies: [
    {
      id: 33,
      logo_path: "/8lvHyhjr8oUKOOy2dKXoALWKdp0.png",
      name: "Universal Pictures",
      origin_country: "US",
    },
    {
      id: 6704,
      logo_path: "/acf3yqGq8Bm9smHwkQGRDVO5CM5.png",
      name: "Illumination Entertainment",
      origin_country: "US",
    },
  ],
  production_countries: [{ iso_3166_1: "US", name: "United States of America" }],
  release_date: "2022-06-29",
  revenue: 833623000,
  runtime: 87,
  spoken_languages: [{ english_name: "English", iso_639_1: "en", name: "English" }],
  status: "Released",
  tagline: "A villain will rise.",
  title: "Minions: The Rise of asdasas dasd aaslkdasdasd  jaslkd sad a asdjGru",
  video: false,
  vote_average: 7.764,
  vote_count: 1586,
};
